baseURL = 'https://ashf0x.github.io/'
languageCode = "en-us"
title = "AshF0x"
theme="archie"

# Syntax Highlighting
pygmentsstyle = "monokai" 
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate=4

[params]
	favicon="/favicon.ico"
	#og_image="https://raw.githubusercontent.com/athul/archie/master/images/archie-dark.png"
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false
	subtitle = "Hi. This is my Blog."
	description = "Archie is a Minimal and Clean theme for Hugo"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ashf0x"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/0xAshFox"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2